ci:
    autofix_prs: false
    skip: [pylint]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
        - id: check-merge-conflict
        - id: check-yaml
        - id: end-of-file-fixer
        - id: name-tests-test
        - id: trailing-whitespace
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -  id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      name: isort (python)
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8-bugbear==24.4.26
            - flake8-builtins==2.5.0
            - flake8-pytest-style==2.0.0
            - pep8-naming==0.13.3
-   repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: ["--rcfile=.pylintrc", "-sn"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.3
  hooks:
    # Only use ruff for pydocstyle comments for now.
    # Consider using it to replace the other tooling later.
    - id: ruff
      args: [--fix]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [pytest-mypy==0.10.3]
        args: [--strict]
