services:
  web:
    build: .
    restart: unless-stopped
    ports:
      # Default to port 8181 but allow it to be overridden by setting
      # DELIBERATE_PRACTICE_PORT as an environment variable.
      - "${DELIBERATE_PRACTICE_PORT:-8181}:8181"
    develop:
      watch:
        - action: sync
          path: .
          target: /
    env_file:
      - path: "./default.env"
        required: true
      - path: "./user.env"
        required: false
    volumes:
      # Mount the sqlite3 database so it will persist between compose ups and downs.
      - .\database\:/database/
