services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8181:8181"
    develop:
      watch:
        - action: sync
          path: .
          target: /
    env_file:
      - path: "./default.env"
        required: true
      - path: "./user.env"
        required: false
    volumes:
      # Mount the sqlite3 database so it will persist between compose ups and downs.
      - .\database\:/database/
