services:
  web:
    build: .
    ports:
      - "8181:8181"
    develop:
      watch:
        - action: sync
          path: .
          target: /
    env_file:
      - path: "./default.env"
        required: true
      - path: "./user.env"
        required: false

# Up with
# docker compose up
# Down with
# docker compose down
# trigger watch with
# docker compose up --watch
# trigger rebuild with
# docker compose up --build
