name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: deliberate_practice
        environment-file: deliberate_practice.yml
    # Pylint has been unable to run within pre-commit, so run it on it's own.
    - name: Pylint
      run: pylint **.py
    - name: Django Check Migrations
      run: python manage.py makemigrations --check --dry-run --no-input
