name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: pre-commit
      uses: pre-commit/action@v3.0.1
